/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const carrier_Logic = require('./code/carrier-logic');
const connection_Logic = require('./code/connection-logic');
const flight_Logic = require('./code/flight-logic');

class carrierManagementSrv extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'Carrier', async (request, next) => {
            await carrier_Logic(request);
            return next();
        });

        this.on('CREATE', 'Connection', async (request, next) => {
            await connection_Logic(request);
            return next();
        });

        this.on('CREATE', 'Flight', async (request, next) => {
            await flight_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    carrierManagementSrv
};